rewrite syscall/sysret section
dreamportdev/Osdev-Notes pull request #87
Opened 2024-04-29 13:09 UTC by Moldytzu

Adds some tables with example values taken from my OS. Also explains more in-depth the privilege switching that occurs.

2024-04-29 13:37 UTC, DeanoBurrito requested changes
Thanks for the PR! Mostly looks good, nice writing - couple of minor things and then we'll get it merged.
Also feel free to add yourself to the contributors file at `99_Appendices/I_Acknowledgements.md`

2024-04-29 13:37 UTC, DeanoBurrito commented on 06_Userspace/04_System_Calls.md
> +`STAR` has three fields used to set the GDT descriptors of userspace and kernelspace. The low 32 bits are reserved for the handler of 32-bit variant of `syscall`. It's safe to set it to zero if you d
> used to set GDT descriptors of

maybe "that specify the selectors used for", a bit more accurate.

> if you dont target 64-bit code

I think this is backwards, you mean its safe to set to zero if you dont support a 32-bit userspace?

> but not that the 64-bit CS

I think that should be "but note that the 64-bit CS"

2024-04-29 13:37 UTC, DeanoBurrito commented on 06_Userspace/04_System_Calls.md
> +`FMASK` holds a bit mask used to disable certain flags when transitioning control to kernel. Basically, if a bit in `FMASK` is set, the coresponding flag is guranteed to be disabled when entering the
spelling corrections: coresponding -> corresponding, guranteed -> guaranteed.
Maybe 'disabled' is the wrong word here, perhaps say the flag is cleared?

2024-04-29 13:37 UTC, DeanoBurrito commented on 06_Userspace/04_System_Calls.md
> +Finally, we need to tell the CPU we support these instructions and have done all of the above setup. Like many extended features on `x86`, there is a flag to enable them at a global level. For `sysca
minor gripe, but `IA32_EFER` is intel's terminology, I think just `EFER` is clear enough.

2024-04-30 16:51 UTC, Moldytzu commented
This might be it :) Thanks for the suggestions.

2024-04-30 17:49 UTC, Moldytzu commented
oops, I missed an important detail after the tables

2024-05-01 06:49 UTC, merged

2024-05-01 06:49 UTC, DeanoBurrito commented
lgtm, merged.